EstFinancePar:
    type: entity
    table: est_finance_par
    indexes:
        IDX_18FCBB8F759C7BB0:
            columns:
                - programme_fk
        IDX_18FCBB8F662D9B98:
            columns:
                - collecte_fk
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        dateCre:
            type: datetime
            nullable: true
            column: date_cre
        dateMaj:
            type: datetime
            nullable: true
            column: date_maj
        userCre:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: user_cre
        userMaj:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: user_maj
    manyToOne:
        programmeFk:
            targetEntity: Programme
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                programme_fk:
                    referencedColumnName: id
            orphanRemoval: false
        collecteFk:
            targetEntity: Collecte
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                collecte_fk:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
