IndividuLameEstRealisePar:
    type: entity
    table: individu_lame_est_realise_par
    indexes:
        IDX_88295540D9C85992:
            columns:
                - individu_lame_fk
        IDX_88295540B53CD04C:
            columns:
                - personne_fk
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        dateCre:
            type: datetime
            nullable: true
            column: date_cre
        dateMaj:
            type: datetime
            nullable: true
            column: date_maj
        userCre:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: user_cre
        userMaj:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: user_maj
    manyToOne:
        individuLameFk:
            targetEntity: IndividuLame
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                individu_lame_fk:
                    referencedColumnName: id
            orphanRemoval: false
        personneFk:
            targetEntity: Personne
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                personne_fk:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
