#index:
#    path: /
#    controller: App\Controller\DefaultController::index
root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: default_index
        permanent: true